# Generated by Django 5.2.4 on 2025-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon_class', models.CharField(max_length=100, verbose_name='İkon Sınıfı (örn: bi bi-activity)')),
                ('color_class', models.CharField(max_length=50, verbose_name='Renk Sınıfı (örn: item-cyan)')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
