# Generated by Django 5.2.4 on 2025-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banka Adı')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Hesap Sahibi')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT Kodu')),
                ('is_active', models.BooleanField(default=False, help_text='Sadece bir tane aktif hesap olabilir.', verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Banka Hesabı',
                'verbose_name_plural': 'Banka Hesapları',
            },
        ),
    ]
