# Generated by Django 5.2.4 on 2025-08-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_tag_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='URL için benzersiz kısa isim (örn: web-tasarim)', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Portfolyo Kategorisi',
                'verbose_name_plural': 'Portfolyo Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Proje Başlığı')),
                ('slug', models.SlugField(help_text='URL için benzersiz ve boşluksuz kısa isim.', max_length=255, unique=True)),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Müşteri')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('project_url', models.URLField(blank=True, verbose_name='Proje Linki')),
                ('short_description', models.CharField(max_length=255, verbose_name='Kısa Açıklama (Liste Sayfası İçin)')),
                ('long_description', models.TextField(verbose_name='Uzun Açıklama (Detay Sayfası İçin)')),
                ('main_image', models.ImageField(upload_to='portfolio_images/', verbose_name='Ana Proje Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.portfoliocategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Portfolyo Projesi',
                'verbose_name_plural': 'Portfolyo Projeleri',
                'ordering': ['-project_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/details/', verbose_name='Ek Resim')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.portfolioitem', verbose_name='Ait Olduğu Proje')),
            ],
            options={
                'verbose_name': 'Proje Resmi',
                'verbose_name_plural': 'Proje Resimleri',
            },
        ),
    ]
