# Generated by Django 5.2.4 on 2025-08-24 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: ILK2025, YAZINDIRIMI', max_length=50, unique=True, verbose_name='İndirim Kodu')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text="Örn: %15 indirim için '15.00' girin.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Yüzdesi (%)')),
                ('valid_from', models.DateTimeField(verbose_name='Geçerlilik Başlangıç Tarihi')),
                ('valid_to', models.DateTimeField(verbose_name='Geçerlilik Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text="Sınırsız kullanım için '0' olarak bırakın.", verbose_name='Maksimum Kullanım Sayısı')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
            ],
            options={
                'verbose_name': 'İndirim Kodu',
                'verbose_name_plural': 'İndirim Kodları',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Müşteri ID'),
        ),
    ]
