# Generated by Django 5.2.4 on 2025-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfoliocategory_portfolioitem_portfolioimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('title', models.CharField(max_length=100, verbose_name='Unvanı')),
                ('photo', models.ImageField(upload_to='team_photos/', verbose_name='Fotoğraf')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Linki')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Linki')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram Linki')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Linki')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama için kullanılır (küçük sayı önce gelir).')),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
