# Generated by Django 5.2.4 on 2025-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter Linki')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Linki')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
