# Generated by Django 5.2.4 on 2025-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Sayfanın arama motorlarındaki açıklaması (max 160 karakter).', max_length=160, verbose_name='Meta Açıklaması (SEO için)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Sayfanın arama motorlarındaki açıklaması (max 160 karakter).', max_length=160, verbose_name='Meta Açıklaması (SEO için)'),
        ),
    ]
