# Generated by Django 5.2.4 on 2025-08-03 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('logo', models.ImageField(upload_to='client_logos/', verbose_name='Müşteri Logosu')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yetenek Adı (örn: HTML)')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Yüzde Değeri (1-100 arası)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama için kullanılır.')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['order'],
            },
        ),
    ]
