# Generated by Django 5.2.4 on 2025-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Bu görsel, hizmetin detay sayfasında görünecektir.', null=True, upload_to='service_images/', verbose_name='Hizmet Detay Görseli'),
        ),
    ]
