# Generated by Django 5.2.4 on 2025-08-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200, verbose_name='Hikaye Başlığı')),
                ('story_subtitle', models.CharField(max_length=100, verbose_name='Hikaye Alt Başlığı')),
                ('story_description', models.TextField(verbose_name='Hikaye Açıklaması')),
                ('bullet_point_1', models.CharField(max_length=255, verbose_name='Madde 1')),
                ('bullet_point_2', models.CharField(max_length=255, verbose_name='Madde 2')),
                ('bullet_point_3', models.CharField(max_length=255, verbose_name='Madde 3')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Hakkımızda Sayfası Resmi')),
                ('video_url', models.URLField(blank=True, help_text='YouTube veya Vimeo linki.', verbose_name='Video Linki')),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası',
                'verbose_name_plural': 'Hakkımızda Sayfası',
            },
        ),
    ]
