# Generated by Django 5.2.4 on 2025-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Eğer proje satılık ise fiyatını girin. Örneğin: 15000.00', max_digits=10, null=True, verbose_name='Fiyat (TL)'),
        ),
    ]
