# Generated by Django 5.2.4 on 2025-08-15 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Kategorisi', 'verbose_name_plural': 'Blog Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-project_date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='main.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklaması (SEO için)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='long_description',
            field=models.TextField(verbose_name='Uzun Açıklama'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ImageField(upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklaması'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(max_length=100, verbose_name='İkon Sınıfı (Bootstrap Icons)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Hizmet Detay Görseli'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
