# Generated by Django 5.2.4 on 2025-08-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_blogpost_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sipariş/Sepet', 'verbose_name_plural': 'Siparişler/Sepetler'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Sepette'), ('completed', 'Tamamlandı')], default='cart', max_length=10, verbose_name='Durum'),
        ),
    ]
