# Generated by Django 5.2.4 on 2025-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_options_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Fatura E-posta'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura Adı'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Kredi Kartı'), ('debit_card', 'Banka Kartı'), ('bank_transfer', 'Havale/EFT'), ('cash', 'Nakit')], max_length=20, null=True, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlem ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Sepette'), ('pending', 'Ödeme Bekleniyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='cart', max_length=20, verbose_name='Durum'),
        ),
    ]
