# Generated by Django 5.2.4 on 2025-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_billing_address_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Kredi Kartı'), ('debit_card', 'Banka Kartı'), ('bank_transfer', 'Havale/EFT'), ('cash', 'Nakit Ödeme')], max_length=20, null=True, verbose_name='Ödeme Yöntemi'),
        ),
    ]
